CREATE USER 'shorturl'@'localhost' IDENTIFIED BY 'shorturl';
GRANT ALL PRIVILEGES ON * . * TO 'shorturl'@'localhost';
FLUSH PRIVILEGES;
CREATE DATABASE IF NOT EXISTS SHORTURL DEFAULT CHARACTER SET utf8;
SET NAMES 'utf8';

