
CREATE TABLE IF NOT EXISTS `URLS` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT ,
  `SHORT_URL` CHAR(64) NOT NULL,
  `FULL_URL` VARCHAR(4096) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `SHORT_URL_INDEX` (`SHORT_URL`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
